.github/workflows/build-test.yaml

Change github actions on PR for contributors

---

.github/actions/setup/action.yaml
.github/workflows/build-test.yaml

Use step of installing upstream libseccomp as composite action

Use composite github action

---

.codecov.yml
.github/workflows/build-test.yaml
README.md

- Run code coverage test by github actions
- Add codecov badge in README

Add code coverage

---

.github/workflows/build-test.yaml

Trigger CI by pushing to main branch

---

libseccomp/src/lib.rs

- Added test for ScmpCompareOp NotEqual

Update unit tests for ScmpCompareOp NotEqual

---

libseccomp/Cargo.toml

nix seems to be used nowhere in the code, however it is listed as dependency.

Remove unused nix dependency

---

libseccomp/MAINTAINERS

Add MAINTAINERS file

---

libseccomp/src/lib.rs

Rename get_library_version to ScmpVersion::current() and keep it as
deprecated alias.

Rustify get_library_version

---

libseccomp/src/lib.rs

This change will
1. make ScmpArgCompare::new to take only one datum, which is always the
datum.
2. make ScmpCompareOp::MaskedEqual to contain the mask
```rust
// Before
ScmpArgCompare::new(0, ScmpCompareOp::Equal, 32, None);
ScmpArgCompare::new(0, ScmpCompareOp::MaskedEqual, 0xffff, Some(3));
// After
ScmpArgCompare::new(0, ScmpCompareOp::Equal, 32);
ScmpArgCompare::new(0, ScmpCompareOp::MaskedEqual(0xffff), 3);
```
---
closes #35

Make ScmpArgCompare::new easier to understand for new users

---

libseccomp/src/error.rs
libseccomp/src/lib.rs

> **Add From impl for SeccompError**
> This will impl From<std::ffi::NulError|std::num::TryFromIntError|std::str::Utf8Error>
> for SeccompError. These impls are public, but I don't think that's a
> problem.
> 
> Unfortunately does `impl<T: Error> From<T> for SeccompError` not work in
> stable rust yet.
> **Replace map_err with implicit From::from**

SeccompError improvements

---

libseccomp/src/lib.rs

- simplify add_rule
- Make ScmpArgCompare be just a newtype wrapper around scmp_arg_cmp with
the same ABI.
- Add unit test for ScmpArgCompare

Internal refactoring for the add_rule rework

---

README.md
libseccomp/src/lib.rs

Rework add_rule

---

CHANGELOG.md
README.md
libseccomp-sys/Cargo.toml
libseccomp/Cargo.toml

Bump version to 0.2.0

---

CHANGELOG.md
README.md
libseccomp/Cargo.toml

Bump version to 0.2.1

---

CHANGELOG.md
README.md
libseccomp/Cargo.toml

Bump version to 0.2.2

---

CHANGELOG.md
libseccomp/src/lib.rs

Add `reset_global_state()`

---

CHANGELOG.md
libseccomp/src/error.rs
libseccomp/src/lib.rs
libseccomp/src/notify.rs

Make more types usable with HashMap

---

CHANGELOG.md
libseccomp/src/lib.rs
libseccomp/src/notify.rs

Add ScmpSyscall + syscall_resolve_name_rewrite

---

README.md

Update example in README.md to use ScmpSyscall

---

CHANGELOG.md
README.md
libseccomp-sys/Cargo.toml
libseccomp/Cargo.toml

- libseccomp v0.2.3
- libseccomp-sys v0.2.1

Bump version to 0.2.3

---

.github/workflows/build-test.yaml
libseccomp-sys/src/lib.rs

First commit: Fix some typos
Second commit: Add codespell checks to CI

Add spell check

---

CHANGELOG.md
libseccomp/src/notify.rs

Change type of ScmpNotifData.syscall to ScmpSyscall

---

libseccomp/src/api.rs
libseccomp/src/filter_context.rs
libseccomp/src/functions.rs
libseccomp/src/version.rs

Signed-off-by: Savithry J <Savithry.Jayaraman@sony.com>

Example snippets for libseccomp-rs functions.

---

libseccomp/src/notify.rs

Document that the get_notify_fd is shared

---

libseccomp/src/syscall/aarch64.rs
libseccomp/src/syscall/arm.rs
libseccomp/src/syscall/mips.rs
libseccomp/src/syscall/mips64.rs
libseccomp/src/syscall/powerpc.rs
libseccomp/src/syscall/powerpc64.rs
libseccomp/src/syscall/riscv64.rs
libseccomp/src/syscall/s390x.rs
libseccomp/src/syscall/x86.rs
libseccomp/src/syscall/x86_64.rs

Add SPDX license to syscall files

---

CHANGELOG.md
README.md
libseccomp/Cargo.toml

- libseccomp v0.3.0
Ref. #168 

Bump version to 0.3.0

---

.github/workflows/build-test.yaml

Replace action-rs/toolchain with direct rustup

---

.github/workflows/build-test.yaml

Measure test coverage using `cargo-llvm-cov`.

ci: Replace code coverage

---

README.md

Fix the code in README.md to make it more readable.

Fix the code in README

---

CHANGELOG.md

Add missing CHANGELOG

---

CHANGELOG.md
libseccomp/Cargo.toml

Update bitflags to 2.4.0

---

CHANGELOG.md
libseccomp/src/action.rs
libseccomp/src/arch.rs
libseccomp/src/compare_op.rs
libseccomp/src/error.rs
libseccomp/src/filter_attr.rs

Better parsing errors

---

CHANGELOG.md
libseccomp/src/syscall.rs
libseccomp/tests/tests.rs

Add ScmpSyscall::is_error and ScmpSyscall::is_undef

---

CHANGELOG.md
libseccomp/src/lib.rs
libseccomp/src/syscall.rs
libseccomp/tests/tests.rs

Add RawSyscall interface

---

.github/workflows/build-test.yaml
Makefile
libseccomp/src/lib.rs
libseccomp/src/syscall.rs

`cargo +nightly fmt --all -- --config format_code_in_doc_comments=true`

Run rustfmt on code in doc comments
