libseccomp-rs/libseccomp-rs

- libseccomp/src/lib.rs
- Unit tests have been added for ScmpCompareOp - SCMP_CMP_LT, SCMP_CMP_EQ, SCMP_CMP_GE, SCMP_CMP_GT, SCMP_CMP_MASKED_EQ to obtain code coverage
- Added unit test for error scenario - SeccompError when SCMP_INVALID_FLAG is provided
Signed-off-by: Savithry <savithry.jayaraman@sony.com>
> Adding unit test for ScmpCompareOp

- libseccomp/src/lib.rs
- Unit tests have been added for ScmpFilterAttr - SCMP_FLTATR_ACT_DEFAULT , SCMP_FLTATR_ACT_BADARCH, SCMP_FLTATR_CTL_NNP, SCMP_FLTATR_CTL_TSYNC, SCMP_FLTATR_API_TSKIP, SCMP_FLTATR_CTL_SSB, SCMP_FLTATR_CTL_OPTIMIZE, SCMP_FLTATR_API_SYSRAWRC
- Added unit test for error scenario - SeccompError when SCMP_INVALID_FLAG is provided
Signed-off-by: Savithry <savithry.jayaraman@sony.com>
> Adding unit test for ScmpFilterAttr

- libseccomp-sys/src/lib.rs
- libseccomp/src/lib.rs
1. Update `libseccomp_sys::SCMP_ACT_ERRNO` and
`libseccomp_sys::SCMP_ACT_TRACE` to take an `u16` instead of an `u32`.
`man 3 seccomp_rule_add` says that they take an `uint16_t`:
> **SCMP_ACT_ERRNO(uint16_t errno)**
>   The thread will receive a return value of errno when it calls a syscall
>   that matches the filter rule.
>
> **SCMP_ACT_TRACE(uint16_t msg_num)**
>    If  the  thread  is being traced and the tracing process specified the
>    PTRACE_O_TRACESECCOMP option in the call to ptrace(2), the tracing
>    process will be notified, via PTRACE_EVENT_SECCOMP , and the value
>    provided in msg_num  can be retrieved using the PTRACE_GETEVENTMSG option.
2. Update `libseccomp::ScmpAction` accordingly, except for
`ScmpAction::Errno` which take an `c_int` to make …
> Update errno and trace actions [SemVer change]

- libseccomp/src/lib.rs
Vec::len returns an usize which is bigger than an u32 on some platforms.
Let's return an error in the rare cases where you have more than
u32::MAX comparators instead of silently truncating the len.
> add_rule: Return an error if comparators is to long

- libseccomp/src/lib.rs
Deriving Clone for ScmpFilterContext causes double-free (CWE-415) and
use-after-free (CWE-416) with the current Drop implementation.
`double-free.rs`:
```rust
use libseccomp::*;
fn main() -> Result<(), Box<dyn std::error::Error>> {
let filter1 = ScmpFilterContext::new_filter(ScmpAction::Allow)?;
let filter2 = filter1.clone();
drop(filter1);
drop(filter2);
Ok(())
}
```
`use-after-free.rs`:
```rust
use libseccomp::*;
fn main() -> Result<(), Box<dyn std::error::Error>> {
let mut filter = ScmpFilterContext::new_filter(ScmpAction::Allow)?;
drop(filter.clone());
filter.reset(ScmpAction::Allow)?;
Ok(())
}
```
> Security: Do not derive Clone on ScmpFilterContext

- libseccomp/src/lib.rs
- libseccomp/src/notify.rs
Remove all unwraps to replace them with code to return the `SeccompError`
> Remove unwrap for safety

- libseccomp/src/lib.rs
The signatur of seccomp_attr_set is `int seccomp_attr_set(scmp_filter_ctx ctx, enum scmp_filter_attr attr, uint32_t *value);` (note there's `const` in front of `scmp_filter_ctx ctx`).
> Make set_filter_attr to take a &mut self

- libseccomp/src/lib.rs
- Add `get_no_new_privs_bit` function
- Add a unit test for the function
> Add `get_no_new_privs_bit` function

- libseccomp/src/lib.rs
Taking ownership of the output file is bad if you want to do something
with the output (e.g. display to the user or pass to an other program).
Usually you would use `export_bpf(file.try_clone()?)?` to workaround
this. (OT: And remeber to `file.rewind()?`)
However I think it is save to take a &mut.
Using T: AsRawFd instead of file allows to pass types like ChildStdout
as well.
In the future (when io_safety is stabelized), we can change this to take
BorrowedFd.
---
This PR is an alternative to #29.
> export_{pfc,bpf} take a &mut T where T: AsRawFd

- libseccomp/src/lib.rs
Rename get_native_arch() to ScmpAction::native() and keep it as
deprecated alias.
Unresolved:
- native() -- get native arch
- to_native()/from_native() -- ex/import from/to libseccomp-sys types
are two different kinds of "native". Maybe it is worth to rename
to_native to to_raw or to_sys?
> Rustify get_native_arch

- libseccomp/src/lib.rs
man 3 seccomp_syscall_resolve_num_arch:
> In the case of seccomp_syscall_resolve_num_arch() the associated syscall name
> is returned and it remains the callers responsibility to free the returned
> string via free(3).
> Fix memory leak in get_syscall_name_from_arch

- libseccomp/src/lib.rs
A macro to create `ScmpArgCompare` in a more elegant way.
Relates to #41.
> Add scmp_cmp! macro

- .github/actions/setup/action.yaml
- .github/workflows/build-test.yaml
This PR contains two changes.
1. Refactor libseccomp install action
- Make `LIBSECCOMP_VERSION` variable to make it easier to change the version
1. Add static link check to CI
-  Currently, `libseccomp-rs` supports statically linking with libseccomp library, so run the test by CI.
> Add static link test

- README.md
- libseccomp/src/lib.rs
Use dup3 system call instead of dup2 because
the dup2 is obsolete on aarch64 and the test fails
In addtion, refactor some sample code.
> Use dup3 instead of dup2

- libseccomp/src/error.rs
This PR contains the following 4 commits.
1. Add `Debug` trait for `SeccompError` by hand to output an error message
- Besides, an unresolved error, `EINVAL`, `ECANCELED` and `ParseError` message
2. Create `const` variables for error message
-  Besides, add `ENOENT` and `ERANGE` message
3. Remove `code` field in `SeccompError` struct
4. Add unit tests for `SeccompError`
> Improve `SeccompError`

- .github/workflows/build-test.yaml
- scripts/install_libseccomp.sh
This PR has the following two commits.
1. ci/scripts: Run build/test against each libseccomp version 
- Do compile and test against the `2.4.3`, `2.5.1`, and `2.5.3` that is the latest released version.
- Modify `install_libseccomp.sh` to be able to install arbitrary libseccomp version specified by the option(-v)
1. Combine jobs in CI
- Combine fmt and clippy check
- Combine build and unit test
> ci/scripts: Run build/test against each libseccomp version 

- libseccomp/src/lib.rs
These functions of the upstream libseccomp library return zero on success
or negative error codes on failure.
However, in the older version, some functions return positive
error codes on failure, so some libseccomp-rs APIs may return Ok even if
the function of libseccomp library fails.
For example, until libseccomp v2.4.4, `seccomp_export_pfc` returns
positive error codes on failure.
> Return Err when the return value of the libseccomp library is not zero

- .github/workflows/build-test.yaml
- libseccomp/build.rs
In order to use the libseccomp library installed by our script,
not the library in Ubuntu image of GiHub Actions, we install the
libseccomp library for dynamically linking against gnu-libc into
specified directory. Then, link the complied library forcibly using LD_LIBRARY_PATH.
> CI: Link the libseccomp library compiled by our script

- libseccomp/src/lib.rs
Add unit tests for `export_bpf` and `export_pfc` function
to increase test coverage.
> Add unit tests for `export_bpf` and `export_pfc`

- libseccomp/src/lib.rs
Add tests for `get_library_version` and `get_native_arch` that are
deprecated functions in order to increase test code coverage.
> Add tests for deprecated functions

- libseccomp/src/lib.rs
`set_syscall_priority` sets the priority of a given syscall.
Fixes: #40
> Add set_syscall_priority function

- .gitignore
The `tool` directory was removed by #36.
Hence, we remove `tool/target` in `.gitignore`.
> Remove tool/target in .gitignore

- Makefile
Add SPDX license identifier and Copyright to `Makefile`.
> Add SPDX and Copyright to Makefile

- .github/workflows/build-test.yaml
Add a package's documentation check to CI in order to
confirm that `cargo doc` can generate the documentations
without any warnings and errors.
> Add documentation check to CI

- .github/workflows/build-test.yaml
- Makefile
- libseccomp/build.rs
- libseccomp/src/lib.rs
- libseccomp/src/notify.rs
This commit reworks user notification implementation for safety.
All previous interfaces were changed.
Fixes: #42
> Rework seccomp user notification

- README.md
- libseccomp/src/error.rs
- libseccomp/src/lib.rs
Currently, the format of doc comments is not consistent.
Hence, this commit decides the format as follows in the crate.
This format is based on https://doc.rust-lang.org/rust-by-example/meta/doc.html
The doc comments of function:
```
/// Brief summary of the function on one line. (Start from "verb-s")
///
/// Detailed description of the function. (if you have)
///
/// Description of return value on success.
/// (Start from "This function returns...")
///
/// # Arguments (if the function has arguments)
///
/// * `arg` - Descripition of the argument
///
/// # Errors (if the function returns `Result`)
///
///  If this function encounters..., an error will be returned.
///
/// # Panics (if the function can `panic`)
///
///  Panics if...
///
/// # Examples (if you want to show the example)
/// …
```
> Make the format of doc comments consistent

- CHANGELOG.md
- libseccomp/Cargo.toml
- libseccomp/src/lib.rs
Fix docs.rs build to make the notify module visible in the documentations.
> Make the notify module visible in the docs

- CHANGELOG.md
- libseccomp/src/lib.rs
Re-fix docs.rs build to make the notify module visible
in the documentations using `doc_cfg` feature.
> Make the notify module visible in the docs using doc_cfg

- .gitignore
This also ignores libseccomp/target and libseccomp-sys/target
> gitignore: Cover all target directories

- CHANGELOG.md
- libseccomp/src/lib.rs
`ScmpArch::from_str()` supports for converting `"SCMP_ARCH_MIPS64N32"`
string into `ScmpArch`.
> Add "SCMP_ARCH_MIPS64N32" to ScmpArch::from_str()

- libseccomp/src/lib.rs
Create `test_parse_filter_attr()`, `test_parse_compare_op()`,
`test_parse_action()`, and `test_parse_arch()` functions to replace
the exsiting `test_parse()` function.
Closes: #11
Closes: #64
> Refactor unit tests for parsing

- libseccomp/Cargo.toml
Specify libc version in `Cargo.toml` by Semantic Versioning.
> Specify libc version by SemVer

- libseccomp/src/lib.rs
seccomp_syscall_resolve_name_arch resolves the given syscall name to the
syscall number (or pseudo number) it has on the give architectur.
If you are not running on this archtecture, the result isn't the native
number of the syscall.
seccomp_rule_add interprets the given syscall number for the native
archtecture. Passing a number resolved for a foreign architecture, gives
you any result but not what you want. In the best case this number is
invalid for you native architecture and a error is returend, but it is
also possible that the number is valid, then the blocked syscall is any
arbitrary syscall.
> Fix misleading example

- README.md
Add doc comment format to README.md's contributing section
Also add a changelog link to make the changelog directly accessible from crates.io.
> Add doc comment format to README.md's contributing section

- CHANGELOG.md
- libseccomp/src/lib.rs
This commit adds the following two functions
- `get_badarch_action()` to get the default action taken when the
loaded filter does not match the architecture  of the executing application.
- `set_badarch_action()` to set the default action taken when the
loaded filter does not match the architecture  of the executing application.
> Add {get,set}_badarch_action function

- libseccomp/src/lib.rs
Use `ScmpSyscall::from_name()` insetead of `get_syscall_from_name()`
in the examples code because the `get_syscall_from_name()` was deprecated
by #82.
> examples: Use ScmpSyscall::from_name in the examples.

- Makefile
- Add `test` to `make check`.
- Make default target `build`.
- Set `.PHONY` on one line.
> makefile: Refactor the Makefile

- CHANGELOG.md
- libseccomp/src/lib.rs
Add `get_default_action()` to get the default action as specified in the
call to `new_filter()` or `reset()`.
> api: Add get_default_action()

- CHANGELOG.md
- libseccomp/src/lib.rs
Rename `{get,set}_badarch_action` function to `{get,set}_act_badarch`.
> api: Rename {get,set}_badarch_action to {get,set}_act_badarch

- CHANGELOG.md
- libseccomp/src/lib.rs
Rename `get_default_action` function to `get_act_default`.
> api: Rename get_default_action to get_act_default

- libseccomp-sys/src/lib.rs
- libseccomp/src/lib.rs
- libseccomp/src/notify.rs
This adds #[must_use] to all functions in libseccomp suggested by
cargo clippy -- --warn clippy::must_use_candidate
> Add #[must_use] to some function in libseccomp

- CHANGELOG.md
- libseccomp/src/lib.rs
To make the name of get/set functions for filter attributes consistent,
rename `{get,set}_no_new_privs_bit` to `{get,set}_ctl_nnp`.
> Rename {get,set}_no_new_privs_bit to {get,set}_ctl_nnp

- CHANGELOG.md
- libseccomp/src/lib.rs
Add `ScmpFilterContext::{get,set}_ctl_ssb()` to get/set the state of
`ScmpFilterAttr::CtlSsb` attribute.
> Add ScmpFilterContext::{get,set}_ctl_ssb

- CHANGELOG.md
- libseccomp/src/lib.rs
Add `ScmpFilterContext::{get,set}_ctl_optimize` to get/set the
optimization level of `ScmpFilterAttr::CtlOptimize` attribute.
> Add ScmpFilterContext::{get,set}_ctl_optimize

- CHANGELOG.md
- libseccomp/src/lib.rs
Add `ScmpFilterContext::{get,set}_api_sysrawrc` to get/set the state
of `ScmpFilterAttr::ApiSysRawRc` attribute.
> Add ScmpFilterContext::{get,set}_api_sysrawrc

- CHANGELOG.md
- libseccomp/src/lib.rs
Add `ScmpFilterContext::{get,set}_ctl_tsync()` to get/set the state of
`ScmpFilterAttr::CtlTsync` attribute.
> Add ScmpFilterContext::{get,set}_ctl_tsync

- libseccomp-sys/build.rs
The build for libseccomp-sys emits an error with a message explicitly
when the link type is specified as `framework` because seccomp is a
Linux specific technology and it is not available on OSX.
> build: Emit an error explicitly when link type is framework

- libseccomp-sys/build.rs
- libseccomp/build.rs
Use const variable for `LIBSECCOMP_LINK_TYPE` and
`LIBSECCOMP_LIB_PATH` environment variables.
> build: Use const variable for LIBSECCOMP_{LINK_TYPE,LIB_PATH}

- libseccomp/src/lib.rs
- libseccomp/src/notify.rs
Use a function for non-zero checks where possible and simplify
is_arch_present.
Fixes #72
> Refactor error checks

- .gitmodules
Remove the third party directory from libseccomp-sys to stay out license discussion.
> Remove third-party directory from libseccomp-sys

- libseccomp/src/lib.rs
The descritpion for `set_ctl_nnp` when the argument is `state==true`
is wrong, so remove the comment.
> Fix doc comment for set_ctl_nnp

- libseccomp/src/lib.rs
Current example code for `is_arch_present` fails on aarch64
because native architecture is added to a filter by default.
Hence, remove `assert!(!ctx.is_arch_present(ScmpArch::Aarch64)?);`.
> example: Fix is_arch_present for aarch64

- CHANGELOG.md
- libseccomp/src/lib.rs
- libseccomp/tests/notify.rs
Re-export notify module with private so that users can use the more
convenient structure. This is a breaking change because the notify
module's visibility is no longer public. We do this intentionally
to keep the documentation clean.
Fixes: #130
> Re-export notify module

- libseccomp/src/action.rs
- libseccomp/src/api.rs
- libseccomp/src/arch.rs
- libseccomp/src/compare_op.rs
- libseccomp/src/filter_attr.rs
- libseccomp/src/filter_context.rs
- libseccomp/src/notify.rs
Fix warnings reported by
- `cargo clippy -- -W clippy::pedantic -A clippy::module_name_repetitions -A clippy::wildcard_imports -A clippy::enum_glob_use`
- `cargo clippy -- -W clippy::nursery -A clippy::option_if_let_else -A clippy::redundant_pub_crate -A clippy::missing_const_for_fn`
that sound legit.
> Fix extra clippy warnings

- CHANGELOG.md
- libseccomp/src/api.rs
- libseccomp/src/arch.rs
- libseccomp/src/error.rs
- libseccomp/src/filter_context.rs
- libseccomp/src/functions.rs
- libseccomp/src/lib.rs
- libseccomp/src/notify.rs
- libseccomp/src/syscall.rs
- libseccomp/src/version.rs
- libseccomp/tests/notify.rs
- libseccomp/tests/tests.rs
Closes #134
Closes #137
Public changes:
- Add `SeccompError::errno` + `SeccompErrno` to query the errno returned
by the libseccomp API. (#137)
- Change `add_arch`/`remove_arch` to return `Ok(false)` if the
architecture was already present/not present in the filter and
`Ok(true)` if the architecture was really added/removed
(**Incompatible change**). (#137)
- Change `get_api` to return `u32` instead of `Result<u32>`
(**Incompatible change**).
- Change `ScmpArch::native()` to panic instead of returning an error
(**Incompatible change**).
- Remove `get_native_arch()`
- Make `ErrorKind` and `Result` private.
Internal changes:
- Add `SeccompError::with_msg` and `SeccompError::with_msg_and_source`
(dead_code ATM) as sugar for `SeccompError::new(Common("..."))`.
- Add `SeccompError::from_errno` …
> Rework SeccompError

- .github/workflows/build-test.yaml
Add readme check to verify that libseccomp-rs version is up to
date in the `README.md`.
This prevents you from fogetting to update th `README.md` when upgrading
the version in `libseccomp/Cargo.toml`.
> ci: Add readme check to Github Action

- .github/workflows/build-test.yaml
Add cross compilation test for supported architectures to CI in order
to check if the libseccomp crate can be built for the architectures.
In this test, we just use the libseccomp deb package for dynamic linking.
This test will be helpful for https://github.com/libseccomp-rs/libseccomp-rs/pull/125.
Target architectures for the cross compilation:
- x86, aarch64, arm, mips, mips64, powerpc, powerpc64, riscv, and s390x
> ci: Add cross compilation test for supported architectures

- CHANGELOG.md
- libseccomp/src/notify.rs
- libseccomp/tests/notify.rs
These structs mirror the kernel types which may change with future development in the kernel.
Fixes #172
> Mark notify structs non_exhaustive

- .github/dependabot.yml
This will keep the used actions in your worklfows up-to-date.
As a future step we can also [follow GitHub Actions security best practice](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions) and pin actions to a full length commit SHA.
> Dependabot: Add package-ecosystem github-actions

- libseccomp/src/arg_compare.rs
```rust
let comperators: &[ScmpArgCompare] = &[scmp_cmp!($arg0 & 123 == 123)];
```
Used to work before fe7bd6a/#143 but fail now with "creates a temporary which is freed while still in use". Refactoing the macro back to CallExpression instead of BlockExpression as utmost token fixes it. However IIRC there was a reason why I did not made it that way in the first place and IIRC it wasn't working because attributes in that position were unstable. This would effect MSRV (#135). Nevermind, I can not find anything about this in rust/RELEASES.md or with an internet search, neither my tries with older compilers made it fail that why.
> Fix regression from fe7bd6a/#143

- libseccomp/src/filter_context.rs
Socket 'family' is the _first_ arg, not second.  Thus the test should be `$arg0 != AF_UNIX`.
Fixes #189
> Correct `socket` conditional rule example

- .github/workflows/build-test.yaml
cargo-tarpaulin changed the nameing of release artifacts over three month ago. Unmaintained actions-rs/tarpaulin did not picked it up until now breaking CI.
Ref: https://github.com/actions-rs/tarpaulin/issues/15
We still want to replace the action with an other action, an direct call to cargo-taroaulin or use grcov, see #188.
> Comment coverage job for now

- CHANGELOG.md
- libseccomp/src/filter_context.rs
- libseccomp/tests/tests.rs
`get_api_sysrawrc` and `set_api_sysrawrc` can now be used with any API level.
> Fix: ScmpFilterContext::{get,set}_api_sysrawrc

- CHANGELOG.md
- libseccomp/src/filter_context.rs
- libseccomp/tests/tests.rs
`get_ctl_optimize` and `set_ctl_optimize` can now be used with any API level.
> Fix: ScmpFilterContext::{get,set}_ctl_optimize

- libseccomp-sys/src/lib.rs
Add the following architectures:
- 64-bit loongarch64 (https://github.com/seccomp/libseccomp/commit/6966ec77b195ac289ae168c7c5646d59a307f33f)
- 32-bit m68k (https://github.com/seccomp/libseccomp/commit/dd5c9c24e8ba11c9c3ee6b60c93cef64a9ad5c86)
- 32-bit sheb (https://github.com/seccomp/libseccomp/commit/c12945db0b7e32f409ba3a68d18c6d6f6dd22b19)
- 32-bit sh (https://github.com/seccomp/libseccomp/commit/c12945db0b7e32f409ba3a68d18c6d6f6dd22b19)
Add the following action:
- `SCMP_FLTATR_CTL_WAITKILL` (https://github.com/seccomp/libseccomp/commit/96989965042a515a3cbcb50e9b98243b9b7d4c37)
Add the following functions:
- `seccomp_export_bpf_mem` (https://github.com/seccomp/libseccomp/commit/3f0e47fe2717b73ccef68ca18f9f7297ee73ebb2)
- `seccomp_precompute` …
> sys: Add new raw architectures, action, and functions

- CHANGELOG.md
- libseccomp/Cargo.toml
- libseccomp/src/notify.rs
- libseccomp/tests/notify.rs
- bitflags is part of our public API
- bitflags 2 has breaking changes
- bitflags 2 had a turbulent beginning, I therefore pinned it to it's minor release (patch release behave normally).
Fixes #197
~~CI will fail because of msrv.~~
> Bump bitlfags to 2.3

- .github/workflows/build-test.yaml
- scripts/install_libseccomp.sh
In order to test new APIs that haven't released officially yet in the upstream libseccomp library, add the CI test for them using the main of the upstream repository.
> ci: Add test for the upstream libseccomp library

- .github/workflows/build-test.yaml
In order to test new APIs that haven't released officially yet in the upstream libseccomp library, add the CI test for them using the main of the upstream repository.
Expands: #225
> ci: msrv and coverage jobs use the main branch of the libseccomp

- .github/workflows/build-test.yaml
- CHANGELOG.md
- README.md
- libseccomp/build.rs
- libseccomp/src/filter_context.rs
- libseccomp/src/lib.rs
- libseccomp/src/version.rs
- libseccomp/tests/notify.rs
- libseccomp/tests/tests.rs
Drop the libseccomp < 2.5.0 support to simplify the code because the upstream no longer supports libseccomp < 2.5.0.
Fixes: #214
> Drop the libseccomp < 2.5.0 support

- CHANGELOG.md
- libseccomp/src/error.rs
The `SeccompError::sysrawrc()` api queries the system's raw error code returned
when something goes wrong in the libc and the kernel. This api will be useful
for users who want to extract the system's error code directly returned by the
`ScmpFilterAttr::ApiSysRawRc`, or get the errno returned by the libseccomp API
as a negative integer rather than `SeccompErrno`.
For example, with `ScmpFilterAttr::ApiSysRawRc` enabled, the `ScmpFilterContext::load()`
and `ScmpFilterContext::export_{bpf,pfc}()` have a possibility that returns
system's error codes such as `EBUSY`, `EBADF`, etc. These error codes are not
extracted by `SeccompError::errno()`. Instead, you can use `SeccompError::sysrawrc()`
that deals with all the system error codes returned by the system.
Regarding the usage in detail, refer …
> error: Add SeccompError::sysrawrc() api

- libseccomp/src/error.rs
- libseccomp/tests/tests.rs
Covered the following functions:
- `SeccompError::with_msg()`
- `SeccompError::with_msg_and_source()`
- `SeccompError::errno()`
- `SeccompErrno::fmt()`
- `ScmpFilterContext::new_filter()` (deprecated function)
> test: Improve test coverage

- CHANGELOG.md
- libseccomp/src/filter_context.rs
- libseccomp/tests/tests.rs
> `seccomp_export_bpf_mem`

- .github/workflows/build-test.yaml
- Makefile
- libseccomp/Cargo.toml
- libseccomp/src/syscall.rs
Allow the crates.io documentation to show `ScmpSyscall::new()` provided by the `const-syscall` feature with the following annotation.
> Available on crate feature `const-syscall` only.
This is enabled by the `doc_cfg` feature which is available in only the nightly channel, but the `docs.rs` of crates.io is built by the nightly so we don't worry about it. 
Ref. https://docs.rs/about/builds
> doc: Show ScmpSyscall::new of const-syscall  with annotation

- .github/workflows/build-test.yaml
`mips-unknown-linux-gnu` and `mips64-unknown-linux-gnuabi64` have been dropped to Tier 3 since rust 1.72 by https://github.com/rust-lang/compiler-team/issues/648.
Hence, they are no longer available even in the nightly channel.
> ci: Drop mips/mips64 target from CI

- libseccomp/src/filter_context.rs
Replace `ScmpFilterContext::new_filter()` with `ScmpFilterContext::new()` due to the deprecated function.
> example: Stop using ScmpFilterContext::new_filter

- .github/actions/setup/action.yaml
- .github/workflows/build-test.yaml
- libseccomp/tests/tests.rs
Add our composite action to setup the upstream libseccomp for the crate.
Currently, we write(copy-paste) the same steps to install the libseccomp in various jobs, but it is not good in terms of maintainability.
Let's replace them with the composite action.
> ci: Add setup action to install upstream libseccomp

- .github/workflows/build-test.yaml
Run schedule job at UTC 01:00 every day to detect a failure early. Besides, enable workflow dispatch to be able to run workflow manually.
> ci: Enable daily build and workflow dispatch

- .github/workflows/build-test.yaml
LLVM's address sanitizer(asan) is very useful to find memory errors such as use after free, memory leaks, and so on.
The libseccomp-rs uses many unsafe blocks in it's library codes and test codes, so asan helps us write safe codes.
> ci: Enable address sanitizer

- .github/actions/setup/action.yaml
The musl build(`./install_libseccomp -m`) is enabled only in the `static-link-musl` job.
> ci: musl build is enabled only in `static-link-musl` job.

- CHANGELOG.md
Add a description for the change of `check_version` logic to `CHANGELOG` because the update causes a silent breaking, not caught by compiler.
Fixes: https://github.com/libseccomp-rs/libseccomp-rs/issues/252
> Add the change of `check_version` to `CHANGELOG`

- libseccomp/build.rs
- libseccomp/tests/tests.rs
check_api is good enough to pass the test of `set_ctl_waitkill` on an environment which is not satisfied with the condition of the api.
> test: Replace github_action cfg with check_api

- libseccomp/src/syscall.rs
- libseccomp/tests/tests.rs
The syscall with the longest name currently is
sched_rr_get_interval_time64 with 28 bytes/chars.
> from_name*: Use stack allocated c-string

- CHANGELOG.md
- libseccomp/src/filter_context.rs
- libseccomp/tests/tests.rs
Add `ScmpFilterContext::{get, set}_api_tskip` to get/set the state of `ScmpFilterAttr::ApiTskip` attribute. 
Fixes: #117
> Add ScmpFilterContext::{get, set}_api_tskip

- .github/workflows/build-test.yaml
- CHANGELOG.md
- libseccomp-sys/Cargo.toml
- libseccomp-sys/src/lib.rs
- libseccomp/Cargo.toml
- libseccomp/src/filter_context.rs
- libseccomp/tests/tests.rs
The followiing three functions are added:
- `ScmpFilterContext::start_transaction`
- `ScmpFilterContext::commit_transaction`
- `ScmpFilterContext::reject_transaction`
These functions are available since libseccomp v2.6.0.
> Add transaction support

- CHANGELOG.md
- README.md
- libseccomp-sys/Cargo.toml
- libseccomp-sys/README.md
- libseccomp/Cargo.toml
- libseccomp: v0.4.0
- libseccomp-sys: v0.3.0
> Bump version to 0.4.0
